// Central registry of audit action strings. Keeping these as constants
// (rather than inline string literals at each call site) avoids typos
// silently producing unqueryable audit records.
export const AuditAction = {
  ORGANIZER_REGISTERED: "ORGANIZER_REGISTERED",
  ORGANIZER_PROFILE_UPDATED: "ORGANIZER_PROFILE_UPDATED",
  ORGANIZER_APPLICATION_SUBMITTED: "ORGANIZER_APPLICATION_SUBMITTED",
  ORGANIZER_APPROVED: "ORGANIZER_APPROVED",
  ORGANIZER_REJECTED: "ORGANIZER_REJECTED",
  ORGANIZER_SUSPENDED: "ORGANIZER_SUSPENDED",
  ORGANIZER_STATUS_OVERRIDDEN: "ORGANIZER_STATUS_OVERRIDDEN",

  USER_REGISTERED: "USER_REGISTERED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",
  EMAIL_VERIFIED_BY_ADMIN: "EMAIL_VERIFIED_BY_ADMIN",
  PHONE_VERIFIED: "PHONE_VERIFIED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET: "PASSWORD_RESET",

  ELECTION_CREATED: "ELECTION_CREATED",
  ELECTION_UPDATED: "ELECTION_UPDATED",
  ELECTION_SUBMITTED: "ELECTION_SUBMITTED",
  ELECTION_APPROVED: "ELECTION_APPROVED",
  ELECTION_REJECTED: "ELECTION_REJECTED",
  ELECTION_LAUNCHED: "ELECTION_LAUNCHED",
  ELECTION_CLOSED: "ELECTION_CLOSED",
  ELECTION_DELETED: "ELECTION_DELETED",
  ELECTION_STATUS_OVERRIDDEN: "ELECTION_STATUS_OVERRIDDEN",
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];

export const AuditEntityType = {
  USER: "USER",
  ORGANIZER_PROFILE: "ORGANIZER_PROFILE",
  ELECTION: "ELECTION",
} as const;

export type AuditEntityTypeValue = (typeof AuditEntityType)[keyof typeof AuditEntityType];
